### ISSUE TITLE
请问 下面两段脚本是什么作用 

### ISSUE THREAD

**Issue by xiaolongyuan** [douban/rexxar-web#10]
来自 http://img3.doubanio.com/dae/rexxar/files/subject/subject-34a447e5c0.html
```
 <script>
      window.Rexxar = window.Rexxar || {};
      window.Rexxar.Lifecycle = window.Rexxar.Lifecycle || {};
      window.Rexxar.Lifecycle.onPageVisible = function() {};
      window.Rexxar.Lifecycle.onPageInvisible = function() {};
    </script>
```

下面的 VENDOR_START VENDOR_END 是在哪设置的呢？
```
 <script>
      if (!window.VENDOR_START) {
        logSend('Vendor assets failed to load.');
        var reloadBtn = document.createElement('div');
        reloadBtn.style.fontSize = '14px';
        reloadBtn.style.color = '#494949';
        reloadBtn.style.margin = '12px';
        reloadBtn.appendChild(document.createTextNode('点击重试'));
        reloadBtn.addEventListener('click', function() {
          window.location.reload();
        });
        showErrorMsg("资源加载失败啦 :(", reloadBtn);
      } else if (window.VENDOR_START && !window.VENDOR_END) {
        logSend('Vendor assets load incomplete.');
        var reloadBtn = document.createElement('div');
        reloadBtn.style.fontSize = '14px';
        reloadBtn.style.color = '#494949';
        reloadBtn.style.margin = '12px';
        reloadBtn.appendChild(document.createTextNode('点击重试'));
        reloadBtn.addEventListener('click', function() {
          window.location.reload();
        });
        showErrorMsg("资源加载失败啦 :(", reloadBtn);
      }
    </script>
```

**Comment by xiaolongyuan** [comment]
![image](https://cloud.githubusercontent.com/assets/3142363/23784651/372be274-059e-11e7-92cb-51252cd44180.png)

VENDOR_START VENDOR_END  这两个变量由来知道了

**但是如何打包进 vendor.js 呢？**

**Comment by ianwith** [comment]
@xiaolongyuan 

我们在自己的打包流程中加了两个变量，当然，根据你自己的业务需求，你可能完全不需要这么做

比如
```
      if (file.basename === 'vendor.js') {
        let content = file.contents.toString('utf8');
        let newContent = [
          'window.VENDOR_START=true;',
          content,
          'window.VENDOR_END=true;'
        ].join('\n');
        file.contents = new Buffer(newContent);
        file.hash = revHash(file.contents);
      }
```

**Comment by xiaolongyuan** [comment]
您好  打包时 出现这个错误(gulp serve 启动开发 是正常的)：

webpack 版本：
```
  "webpack": "^2.2.1",
    "webpack-bundle-analyzer": "^2.2.1",
    "webpack-dev-middleware": "^1.10.0",
    "webpack-hot-middleware": "^2.16.1",
    "webpack-merge": "^2.6.1",
    "webpack-stream": "^3.2.0",
```

![image](https://cloud.githubusercontent.com/assets/3142363/23981384/1cfa40a6-0a41-11e7-806a-76de90002fb9.png)

**Comment by xiaolongyuan** [comment]
webpack.config.js

```
var path = require('path');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var utils = require('./build/utils')
var config = require('./config')
var vueLoaderConfig = require('./build/vue-loader.conf')
const vuxLoader = require('vux-loader')

function resolve (dir) {
  // return path.join(__dirname, '..', dir)
  return path.join(__dirname, dir)
}

module.exports = function(env) {
  var webpackConfig = {
    entry: {},
    output: {
      filename: '[name].js'
    },
    resolve: {
      extensions: ['.js', '.vue', '.json'],
      alias: {
        'vue$': 'vue/dist/vue.esm.js',
        'src': resolve('src'),
        '@': resolve('src'),
        common: resolve('src/common')
      }
    },
    module: {
      rules: [
        {
          test: /\.vue$/,
          loader: 'vue-loader',
          options: vueLoaderConfig
        },
        {
          test: /\.js$/,
          loader: 'babel-loader',
          include: [resolve('src'), resolve('test')]
        },
        {
          test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
          loader: 'url-loader',
          query: {
            limit: 10000,
            name: utils.assetsPath('img/[name].[hash:7].[ext]')
          }
        },
        {
          test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
          loader: 'url-loader',
          query: {
            limit: 10000,
            name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
          }
        },
        // {
        //   test: /\.(css|scss)$/,
        //   loader: ExtractTextPlugin.extract('style',
        //     'css?modules,camelCase=dashes,localIdentName=' + (
        //       env === 'production' ?
        //         '[hash:base64:5]' :
        //         '[folder]--[local]--[hash:base64:5]'
        //     )
        //   )
        // },
        // {
        //   test: /\.(css|scss)$/,
        //   loader: ExtractTextPlugin.extract({
        //     fallback: 'style-loader',
        //     use: 'css-loader?modules,camelCase=dashes,localIdentName=' + (
        //       env === 'production' ?
        //         '[hash:base64:5]' :
        //         '[folder]--[local]--[hash:base64:5]'
        //     )
        //   })
        // }
      ]
    },
    // eslint: {
    //   configFile: '.eslintrc'
    // },
    plugins: [
      // new ExtractTextPlugin({ filename: '[name].css',
      //   disable: env === 'production' ? false : true,
      //   allChunks: true
      // })
    ]
  }

  return vuxLoader.merge(webpackConfig, {
    options: {},
    plugins: [
      {
        name: 'vux-ui'
      },
      {
        name: 'duplicate-style'
      }
    ]
  })
}

```

**Comment by xiaolongyuan** [comment]
deployConfig.js

```
import webpack from 'webpack';
import argv from '../utils/argv';
import getBaseConfig from '../../webpack.config.js';

var merge = require('webpack-merge')
var CopyWebpackPlugin = require('copy-webpack-plugin')
var HtmlWebpackPlugin = require('html-webpack-plugin')
var ExtractTextPlugin = require('extract-text-webpack-plugin')
var OptimizeCSSPlugin = require('optimize-css-assets-webpack-plugin')

import { sources } from '../globals/sources';

let deployConfig = Object.assign({}, getBaseConfig('production'));

deployConfig.entry['vendor'] = ['vue'];
sources.forEach(function(source) {
  let { path, name } = source;
  // console.log(' \n------------ -> path:'+path+' name:'+name)
  deployConfig.entry[`${path}/${name}`] = `./src/${path}/${name}.js`;
});

deployConfig.stats = { children: false };

deployConfig.plugins = deployConfig.plugins.concat(
  new webpack.optimize.OccurrenceOrderPlugin(),
  new webpack.optimize.CommonsChunkPlugin({
    name: 'vendor',
    filename: 'common/vendor.js',
    minChunks: Infinity
  }),
  new webpack.DefinePlugin({
    'process.env': {
      'NODE_ENV': JSON.stringify('production'),
    }
  }),
  new webpack.optimize.UglifyJsPlugin({
    compress: { warnings: false },
    comments: false,
    sourceMap: false
  }),
  // // copy custom static assets
  // new CopyWebpackPlugin([
  //   {
  //     from: path.resolve(__dirname, '../static'),
  //     to: 'common/',
  //     ignore: ['.*']
  //   }
  // ])
);

var utils = require('../../build/utils')
export default merge(deployConfig,{
  module: {
    rules: utils.styleLoaders({
      sourceMap: false,
      extract: true
    })
  },
  plugins: [
    // extract css into its own file
    new ExtractTextPlugin({
      // filename: utils.assetsPath('css/[name].[contenthash].css')
      filename: '[name].css',
      disable: false,
      allChunks: true
    }),
  ]
});


```

**Comment by xiaolongyuan** [comment]
var utils = require('../../build/utils')

```
var path = require('path')
var config = require('../config')
var ExtractTextPlugin = require('extract-text-webpack-plugin')

exports.assetsPath = function (_path) {
  var assetsSubDirectory = process.env.NODE_ENV === 'production'
    ? config.build.assetsSubDirectory
    : config.dev.assetsSubDirectory
  return path.posix.join(assetsSubDirectory, _path)
}

exports.cssLoaders = function (options) {
  options = options || {}

  var cssLoader = {
    loader: 'css-loader',
    options: {
      minimize: process.env.NODE_ENV === 'production',
      sourceMap: options.sourceMap
    }
  }

  // generate loader string to be used with extract text plugin
  function generateLoaders (loader, loaderOptions) {
    var loaders = [cssLoader]
    if (loader) {
      loaders.push({
        loader: loader + '-loader',
        options: Object.assign({}, loaderOptions, {
          sourceMap: options.sourceMap
        })
      })
    }

    // Extract CSS when that option is specified
    // (which is the case during production build)
    if (options.extract) {
      return ExtractTextPlugin.extract({
        use: loaders,
        fallback: 'vue-style-loader'
      })
    } else {
      return ['vue-style-loader'].concat(loaders)
    }
  }

  // http://vuejs.github.io/vue-loader/en/configurations/extract-css.html
  return {
    css: generateLoaders(),
    postcss: generateLoaders(),
    less: generateLoaders('less'),
    sass: generateLoaders('sass', { indentedSyntax: true }),
    scss: generateLoaders('sass'),
    stylus: generateLoaders('stylus'),
    styl: generateLoaders('stylus')
  }
}

// Generate loaders for standalone style files (outside of .vue)
exports.styleLoaders = function (options) {
  var output = []
  var loaders = exports.cssLoaders(options)
  for (var extension in loaders) {
    var loader = loaders[extension]
    output.push({
      test: new RegExp('\\.' + extension + '$'),
      use: loader
    })
  }
  return output
}

```

**Comment by xiaolongyuan** [comment]
我前端库使用的 是 vue.js 2 使用了官方模板的一些配置 开发环境能正常打包 生产环境 报错：

```
Debugger listening on [::]:52533
[15:01:53] Requiring external module babel-register
[15:01:58] Using gulpfile C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\gulpfile.babel.js
[15:01:58] Starting 'clean'...
[15:01:58] Finished 'clean' after 5.91 ms
[15:01:58] Starting 'deploy'...
htmlPipe path:cashbox name:index
htmlPipe path:cashbox name:record
htmlPipe path:cashbox name:cash_balance
htmlPipe path:cashbox name:record_details
htmlPipe path:secret name:tradepasswd_set
htmlPipe path:secret name:tradepasswd_update
htmlPipe path:rexxar name:demo
htmlPipe path:rexxar name:test
C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\webpack\lib\Chunk.js:80
		return this.entrypoints.length > 0;
		                       ^

TypeError: Cannot read property 'length' of undefined
    at Chunk.isInitial (C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\webpack\lib\Chunk.js:80:26)
    at ExtractTextPlugin.<anonymous> (C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\extract-text-webpack-plugin\index.js:302:24)
    at Array.forEach (native)
    at ExtractTextPlugin.<anonymous> (C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\extract-text-webpack-plugin\index.js:301:21)
    at C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\async\dist\async.js:359:16
    at iteratorCallback (C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\async\dist\async.js:935:13)
    at C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\async\dist\async.js:843:16
    at C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\extract-text-webpack-plugin\index.js:297:6
    at C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\async\dist\async.js:359:16
    at iteratorCallback (C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\async\dist\async.js:935:13)
    at C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\async\dist\async.js:843:16
    at C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\extract-text-webpack-plugin\index.js:294:13
    at C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\async\dist\async.js:3025:16
    at eachOfArrayLike (C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\async\dist\async.js:940:9)
    at eachOf (C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\async\dist\async.js:990:5)
    at Object.eachLimit (C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\async\dist\async.js:3089:3)
    at C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\extract-text-webpack-plugin\index.js:268:11
    at C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\async\dist\async.js:3025:16
    at eachOfArrayLike (C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\async\dist\async.js:940:9)
    at eachOf (C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\async\dist\async.js:990:5)
    at Object.eachLimit (C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\async\dist\async.js:3089:3)
    at ExtractTextPlugin.<anonymous> (C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\extract-text-webpack-plugin\index.js:265:10)

Process finished with exit code 1

```

**Comment by ianwith** [comment]
看报错是extract-text-webpack-plugin的问题
1. 看看plugin的版本是否正确
2. 看看webpack配置是否正确
3. Google

**Comment by xiaolongyuan** [comment]
生产环境配置 修改后
```
var utils = require('../../build/utils')
export default merge(deployConfig,{
  module: {
    rules: utils.styleLoaders({
      sourceMap: false,
      extract: true
    })
  },
  plugins: [
    // extract css into its own file
    // new ExtractTextPlugin({
    //   // filename: utils.assetsPath('css/[name].[contenthash].css')
    //   filename: '[name].css',
    //   disable: false,
    //   allChunks: true
    // }),
  ]
});

```

报如下错：

```
[16:03:04] Requiring external module babel-register
[16:03:06] Using gulpfile C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\gulpfile.babel.js
[16:03:06] Starting 'clean'...
[16:03:06] Finished 'clean' after 5.94 ms
[16:03:06] Starting 'deploy'...


======== vux-loader: duplicate-style start~  ========
Starting to optimize CSS...
->-> collect C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\common\vendor.js
(node:23068) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error in plugin 'webpack-stream'
Message:
    Entry module not found: Error: Cannot resolve 'file' or 'directory' ./src/cashbox/index.js in C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp
resolve file
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\cashbox\index.js.js doesn't exist
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\cashbox\index.js.json doesn't exist
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\cashbox\index.js.vue doesn't exist
resolve directory
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\cashbox\index.js\package.json doesn't exist (directory description file)
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\cashbox\index.js is not a directory (directory default file)Entry module not found: Error: Cannot resolve 'file' or 'directory' ./src/cashbox/record.js in C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp
resolve file
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\cashbox\record.js.js doesn't exist
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\cashbox\record.js.vue doesn't exist
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\cashbox\record.js.json doesn't exist
resolve directory
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\cashbox\record.js\package.json doesn't exist (directory description file)
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\cashbox\record.js is not a directory (directory default file)Entry module not found: Error: Cannot resolve 'file' or 'directory' ./src/cashbox/cash_balance.js in C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp
resolve file
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\cashbox\cash_balance.js.js doesn't exist
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\cashbox\cash_balance.js.vue doesn't exist
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\cashbox\cash_balance.js.json doesn't exist
resolve directory
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\cashbox\cash_balance.js\package.json doesn't exist (directory description file)
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\cashbox\cash_balance.js is not a directory (directory default file)Entry module not found: Error: Cannot resolve 'file' or 'directory' ./src/cashbox/record_details.js in C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp
resolve file
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\cashbox\record_details.js.js doesn't exist
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\cashbox\record_details.js.vue doesn't exist
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\cashbox\record_details.js.json doesn't exist
resolve directory
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\cashbox\record_details.js\package.json doesn't exist (directory description file)
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\cashbox\record_details.js is not a directory (directory default file)Entry module not found: Error: Cannot resolve 'file' or 'directory' ./src/secret/tradepasswd_set.js in C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp
resolve file
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\secret\tradepasswd_set.js.js doesn't exist
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\secret\tradepasswd_set.js.vue doesn't exist
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\secret\tradepasswd_set.js.json doesn't exist
resolve directory
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\secret\tradepasswd_set.js\package.json doesn't exist (directory description file)
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\secret\tradepasswd_set.js is not a directory (directory default file)Entry module not found: Error: Cannot resolve 'file' or 'directory' ./src/secret/tradepasswd_update.js in C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp
resolve file
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\secret\tradepasswd_update.js.js doesn't exist
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\secret\tradepasswd_update.js.vue doesn't exist
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\secret\tradepasswd_update.js.json doesn't exist
resolve directory
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\secret\tradepasswd_update.js\package.json doesn't exist (directory description file)
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\secret\tradepasswd_update.js is not a directory (directory default file)Entry module not found: Error: Cannot resolve 'file' or 'directory' ./src/rexxar/demo.js in C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp
resolve file
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\rexxar\demo.js.js doesn't exist
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\rexxar\demo.js.vue doesn't exist
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\rexxar\demo.js.json doesn't exist
resolve directory
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\rexxar\demo.js\package.json doesn't exist (directory description file)
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\rexxar\demo.js is not a directory (directory default file)Entry module not found: Error: Cannot resolve 'file' or 'directory' ./src/rexxar/test.js in C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp
resolve file
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\rexxar\test.js.js doesn't exist
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\rexxar\test.js.vue doesn't exist
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\rexxar\test.js.json doesn't exist
resolve directory
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\rexxar\test.js\package.json doesn't exist (directory description file)
  C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\src\rexxar\test.js is not a directory (directory default file)multi vendor
Module not found: Error: Cannot resolve module 'vue/dist/vue.esm.js' in C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp
resolve module vue/dist/vue.esm.js in C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp
  looking for modules in C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules
    resolve 'file' or 'directory' dist/vue.esm.js in C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\vue
      resolve file
        C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\vue\dist\vue.esm.js.vue doesn't exist
        C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\vue\dist\vue.esm.js.json doesn't exist
        C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\vue\dist\vue.esm.js.js doesn't exist
      resolve directory
        C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\vue\dist\vue.esm.js\package.json doesn't exist (directory description file)
        C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\vue\dist\vue.esm.js is not a directory (directory default file)
[C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\vue\dist\vue.esm.js.vue]
[C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\vue\dist\vue.esm.js.json]
[C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\vue\dist\vue.esm.js.js]
 @ multi vendor
```

**Comment by xiaolongyuan** [comment]
再次修改 
```
    // extract css into its own file
    new ExtractTextPlugin({
      // filename: utils.assetsPath('css/[name].[contenthash].css')
      filename: '[name].css',
      disable: false,
      allChunks: false
    }),
```

错误信息 如下

```
[16:04:56] Using gulpfile C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\gulpfile.babel.js
[16:04:56] Starting 'clean'...
[16:04:56] Finished 'clean' after 6.68 ms
[16:04:56] Starting 'deploy'...
C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\extract-text-webpack-plugin\index.js:267
				var shouldExtract = !!(options.allChunks || chunk.isInitial());
				                                                  ^

TypeError: chunk.isInitial is not a function
    at C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\extract-text-webpack-plugin\index.js:267:55
    at C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\async\dist\async.js:3025:16
    at eachOfArrayLike (C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\async\dist\async.js:940:9)
    at eachOf (C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\async\dist\async.js:990:5)
    at Object.eachLimit (C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\async\dist\async.js:3089:3)
    at ExtractTextPlugin.<anonymous> (C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\extract-text-webpack-plugin\index.js:265:10)
    at Compilation.applyPluginsAsync (C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\webpack-stream\node_modules\tapable\lib\Tapable.js:71:13)
    at Compilation.seal (C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\webpack-stream\node_modules\webpack\lib\Compilation.js:525:7)
    at Compiler.<anonymous> (C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\webpack-stream\node_modules\webpack\lib\Compiler.js:397:15)
    at C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\webpack-stream\node_modules\tapable\lib\Tapable.js:103:11
    at Compilation.<anonymous> (C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\webpack-stream\node_modules\webpack\lib\Compilation.js:445:10)
    at C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\webpack-stream\node_modules\webpack\lib\Compilation.js:417:12
    at C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\webpack-stream\node_modules\webpack\lib\Compilation.js:332:10
    at C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\webpack-stream\node_modules\async\lib\async.js:52:16
    at done (C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\webpack-stream\node_modules\async\lib\async.js:246:17)
    at C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\webpack-stream\node_modules\async\lib\async.js:44:16
    at errorAndCallback (C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\webpack-stream\node_modules\webpack\lib\Compilation.js:202:5)
    at errorOrWarningAndCallback (C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\webpack-stream\node_modules\webpack\lib\Compilation.js:225:13)
    at C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\webpack-stream\node_modules\webpack\lib\Compilation.js:229:12
    at onDoneResolving (C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\webpack-stream\node_modules\webpack\lib\NormalModuleFactory.js:29:20)
    at C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\webpack-stream\node_modules\webpack\lib\NormalModuleFactory.js:85:20
    at C:\Workspace\WebstormProjects\qumei\qm-rexxar-userapp\node_modules\webpack-stream\node_modules\async\lib\async.js:726:13

Process finished with exit code 1
```

**Comment by xiaolongyuan** [comment]
package.json

```
{
  "dependencies": {
    "babel-runtime": "^6.22.0",
    "axios": "^0.15.3",
    "fastclick": "^1.0.6",
    "lscache": "^1.1.0",
    "rexxar-web": "^0.1.0",
    "vue": "^2.2.2",
    "vue-router": "^2.2.0",
    "vuex": "^2.2.1",
    "vux": "^2.1.1-rc.7",
    "es6-promise": "^3.0.2",
    "isomorphic-fetch": "^2.2.0",
    "url-parse": "^1.0.5"
  },
  "devDependencies": {
    "autoprefixer": "^6.7.2",
    "babel-core": "^6.22.1",
    "babel-loader": "^6.2.10",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-es2015-loose": "^7.0.0",
    "babel-preset-latest": "^6.22.0",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",
    "chai": "^3.5.0",
    "chalk": "^1.1.3",
    "connect-history-api-fallback": "^1.3.0",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.26.1",
    "del": "^2.1.0",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.14.1",
    "extract-text-webpack-plugin": "^2.1.0",
    "file-loader": "^0.10.0",
    "friendly-errors-webpack-plugin": "^1.1.3",
    "function-bind": "^1.1.0",
    "gulp": "^3.9.1",
    "gulp-env": "^0.4.0",
    "html-webpack-plugin": "^2.28.0",
    "http-proxy-middleware": "^0.17.3",
    "jade": "^1.11.0",
    "jsdom": "^8.1.0",
    "less": "^2.7.2",
    "less-loader": "^2.2.3",
    "merge-stream": "^1.0.0",
    "minimist": "^1.2.0",
    "mocha": "^2.4.5",
    "opn": "^4.0.2",
    "optimize-css-assets-webpack-plugin": "^1.3.0",
    "ora": "^1.1.0",
    "rev-hash": "^1.0.0",
    "rimraf": "^2.6.0",
    "semver": "^5.3.0",
    "serve-index": "^1.7.2",
    "sinon": "^1.17.3",
    "style-loader": "^0.14.0",
    "through2": "^2.0.0",
    "url-loader": "^0.5.7",
    "vinyl": "^1.2.0",
    "vue-loader": "^11.1.4",
    "vue-style-loader": "^2.0.0",
    "vue-template-compiler": "^2.2.1",
    "vux-loader": "^1.0.46",
    "webpack": "^2.2.1",
    "webpack-bundle-analyzer": "^2.2.1",
    "webpack-dev-middleware": "^1.10.0",
    "webpack-hot-middleware": "^2.16.1",
    "webpack-merge": "^2.6.1",
    "webpack-stream": "^3.2.0",
    "yaml-loader": "^0.4.0"
  },
  "engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
  },
  "browserlist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}

```

**Comment by xiaolongyuan** [comment]
-_- 折腾死了 这个问题

**Comment by xiaolongyuan** [comment]
@ianwith 代码发你邮件了

**Comment by xiaolongyuan** [comment]
马上要上线了 求帮忙
